name: 🔄 Auto-refresh GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  refresh-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Do a blank commit
        run: |
          git config --global user.name "venomblaze-bot"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "🌀 Stats refresh"
          git push
